#include "sdkconfig.h"

// Clock frequency configuration - ESP32 timer runs at 1MHz
#ifndef CONFIG_CLOCK_FREQ
#define CONFIG_CLOCK_FREQ 1000000
#endif

#ifndef CONFIG_LOW_LEVEL_OPTIONS
#define CONFIG_LOW_LEVEL_OPTIONS 0
#endif

#ifndef CONFIG_SERIAL
#define CONFIG_SERIAL 0
#endif

#ifndef CONFIG_SERIAL_BAUD
#define CONFIG_SERIAL_BAUD 0
#endif

#ifndef CONFIG_USBSERIAL
#define CONFIG_USBSERIAL 0
#endif

#ifndef CONFIG_USBCANBUS
#define CONFIG_USBCANBUS 0
#endif

#ifndef CONFIG_USB
#define CONFIG_USB 0
#endif

#ifndef CONFIG_USB_VENDOR_ID
#define CONFIG_USB_VENDOR_ID 0
#endif

#ifndef CONFIG_USB_DEVICE_ID
#define CONFIG_USB_DEVICE_ID 0
#endif

#ifndef CONFIG_USB_SERIAL_NUMBER_CHIPID
#define CONFIG_USB_SERIAL_NUMBER_CHIPID 0
#endif

#ifndef CONFIG_USB_SERIAL_NUMBER 
#define CONFIG_USB_SERIAL_NUMBER 0
#endif


#ifndef CONFIG_NEED_SENSOR_BULK
#define CONFIG_NEED_SENSOR_BULK 0
#endif

#ifndef CONFIG_WANT_GPIO_BITBANGING
#define CONFIG_WANT_GPIO_BITBANGING 0
#endif

#ifndef CONFIG_WANT_DISPLAYS
#define CONFIG_WANT_DISPLAYS 0
#endif

#ifndef CONFIG_WANT_SENSORS
#define CONFIG_WANT_SENSORS 0
#endif

#ifndef CONFIG_WANT_LIS2DW
#define CONFIG_WANT_LIS2DW 0
#endif

#ifndef CONFIG_WANT_LDC1612
#define CONFIG_WANT_LDC1612 0
#endif

#ifndef CONFIG_CANSERIAL
#define CONFIG_CANSERIAL 0
#endif

#ifndef CONFIG_CANBUS
#define CONFIG_CANBUS 0
#endif

#ifndef CONFIG_CANBUS_FREQUENCY
#define CONFIG_CANBUS_FREQUENCY 0
#endif

#ifndef CONFIG_CANBUS_FILTER
#define CONFIG_CANBUS_FILTER 0
#endif

#ifndef CONFIG_INITIAL_PINS
#define CONFIG_INITIAL_PINS ""
#endif

#ifndef CONFIG_HAVE_GPIO
#define CONFIG_HAVE_GPIO 0
#endif

#ifndef CONFIG_HAVE_GPIO_ADC
#define CONFIG_HAVE_GPIO_ADC 0
#endif

#ifndef CONFIG_HAVE_GPIO_SPI
#define CONFIG_HAVE_GPIO_SPI 0
#endif

#ifndef CONFIG_HAVE_GPIO_SDIO
#define CONFIG_HAVE_GPIO_SDIO 0
#endif

#ifndef CONFIG_HAVE_GPIO_I2C
#define CONFIG_HAVE_GPIO_I2C 0
#endif

#ifndef CONFIG_HAVE_GPIO_HARD_PWM
#define CONFIG_HAVE_GPIO_HARD_PWM 0
#endif

#ifndef CONFIG_HAVE_CHIPID
#define CONFIG_HAVE_CHIPID 0
#endif

#ifndef CONFIG_HAVE_STEPPER_BOTH_EDGE
#define CONFIG_HAVE_STEPPER_BOTH_EDGE 0
#endif

#ifndef CONFIG_HAVE_LIMITED_CODE_SIZE
#define CONFIG_HAVE_LIMITED_CODE_SIZE 0
#endif


#ifndef CONFIG_INLINE_STEPPER_HACK
#define CONFIG_INLINE_STEPPER_HACK 0
#endif

#ifndef CONFIG_WANT_SOFTWARE_I2C
#define CONFIG_WANT_SOFTWARE_I2C 0
#endif  //CONFIG_WANT_SOFTWARE_I2C


#ifndef CONFIG_HAVE_STRICT_TIMING
#define CONFIG_HAVE_STRICT_TIMING 0
#endif //CONFIG_HAVE_STRICT_TIMING


#ifndef CONFIG_HAVE_BOOTLOADER_REQUEST
#define CONFIG_HAVE_BOOTLOADER_REQUEST 0
#endif //CONFIG_HAVE_BOOTLOADER_REQUEST


#ifndef CONFIG_WANT_SOFTWARE_SPI
#define CONFIG_WANT_SOFTWARE_SPI 0
#endif //CONFIG_WANT_SOFTWARE_SPI



#define  CONFIG_MACH_AVR 0
#define  CONFIG_MACH_ATSAM 0
#define  CONFIG_MACH_ATSAMD 0
#define  CONFIG_MACH_LPC176X 0
#define  CONFIG_MACH_STM32 0
#define  CONFIG_MACH_HC32F460 0
#define  CONFIG_MACH_RP2040 0
#define  CONFIG_MACH_PRU 0
#define  CONFIG_MACH_AR100 0
#define  CONFIG_MACH_LINUX 0
#define  CONFIG_MACH_SIMU 0
#define  CONFIG_MACH_ESP32 1

// ESP32 specific configurations
#ifndef CONFIG_CLOCK_FREQ
#ifdef CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ * 1000000)
#elif defined(CONFIG_ESP32S2_DEFAULT_CPU_FREQ_MHZ)
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32S2_DEFAULT_CPU_FREQ_MHZ * 1000000)
#elif defined(CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ)
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ * 1000000)
#elif defined(CONFIG_ESP32C3_DEFAULT_CPU_FREQ_MHZ)
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32C3_DEFAULT_CPU_FREQ_MHZ * 1000000)
#elif defined(CONFIG_ESP32C2_DEFAULT_CPU_FREQ_MHZ)
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32C2_DEFAULT_CPU_FREQ_MHZ * 1000000)
#elif defined(CONFIG_ESP32C6_DEFAULT_CPU_FREQ_MHZ)
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32C6_DEFAULT_CPU_FREQ_MHZ * 1000000)
#elif defined(CONFIG_ESP32H2_DEFAULT_CPU_FREQ_MHZ)
#define CONFIG_CLOCK_FREQ (CONFIG_ESP32H2_DEFAULT_CPU_FREQ_MHZ * 1000000)
#else
// Fallback to a reasonable default if no specific CPU frequency is found
#define CONFIG_CLOCK_FREQ 240000000  // 240MHz default
#endif
#endif