#include "sdkconfig.h"

#define CONFIG_MACH_AVR 0
#define CONFIG_HAVE_STRICT_TIMING 0
#define CONFIG_WANT_SOFTWARE_I2C 0
#define CONFIG_INITIAL_PINS 0
#define CONFIG_INLINE_STEPPER_HACK 0
#define CONFIG_SERIAL_BAUD 115200
#define CONFIG_HAVE_BOOTLOADER_REQUEST 0
#define CONFIG_CLOCK_FREQ 160 *10000